create
or replace PROCEDURE SP_TEMP_MHI_TBLMEMBERDETAILS AS BEGIN
/******************************************************************************

NAME:       SP_TEMP_MHI_TBLMEMBERS
PURPOSE:   temp table to target

REVISIONS:
Ver          Date                  Author             Description
---------  ----------          ---------------  ------------------------------------
1.0        05/29/2025       Francis          1. Create SP_TEMP_MHI_TBLMEMBERDETAILS


NOTES:

 ******************************************************************************/
 
--adw_prod_tgt.sp_adw_table_logs('TBLMEMBERDETAILS', 'SP_TEMP_MHI_TBLMEMBERDETAILS', SYSDATE, '', 'DELETE');
DELETE FROM TBLMEMBERDETAILS a
WHERE
    EXISTS (
        SELECT
            1
        FROM
            tblmembers b
        WHERE
            a.membercode = b.membercode
            AND TRUNC (b.dateencoded) >= TRUNC (SYSDATE)
    );

COMMIT;

--adw_prod_tgt.sp_adw_table_logs('TBLMEMBERDETAILS', 'SP_TEMP_MHI_TBLMEMBERDETAILS', SYSDATE, '', 'INSERT');
INSERT INTO
    adw_prod_tgt.TBLMEMBERDETAILS (
        detno,
        compcode,
        membercode,
        memberno,
        importedcode,
        membertype,
        applicationno,
        picturename,
        birthplace,
        telephone,
        mobile,
        emailaddress,
        civilstatus,
        height,
        weight,
        bmiresult,
        bmicategory,
        sssno,
        phno,
        tin,
        vip,
        reapply,
        rts,
        billingprovince,
        payorname,
        employer,
        occupation,
        industry,
        cardreleased,
        homeprovince,
        officeprovince,
        officephone,
        officefax,
        billto,
        zipcodehome,
        zipcodeoffice,
        zipcodebilling,
        billingcity,
        homecity,
        officecity,
        department,
        billingstreet,
        homestreet,
        officestreet,
        ineligible,
        dateineligible,
        renewalplancode,
        medicalremarks,
        bloodtype,
        nationality,
        datehired,
        migrated,
        rowmarker,
        allergies,
        otherhmo,
        deathdate,
        contactperson,
        contactnumber,
        accommodatedby,
        applicationo,
        remarks,
        withph,
        waiver,
        vessel,
        payortin,
        businessstyle,
        provideraccess,
        providerappservices,
        providerappservicesitems,
        pecwaived,
        dental,
        religion,
        withtelemedicine,
        newoccupation,
        monthlyfamilyincome,
        dummymemberno,
        grpprovideraccess,
        grpproviderallowed,
        grpprovidereffectivity,
        parentcompcode,
        pedcovered,
        peddays,
        paymentmethod,
        paymentmethoddetail,
        bankaccttype,
        bankacctno,
        center,
        accountofficer,
        unitmanager,
        province,
        municipality,
        barangay,
        street,
        modeofpayment,
        clienttype,
        repfirstname,
        repminame,
        replastname,
        reprelationship,
        returnstublink,
        placeofbirth,
        last_update_date
    )
SELECT
    detno,
    compcode,
    membercode,
    memberno,
    importedcode,
    membertype,
    applicationno,
    picturename,
    birthplace,
    telephone,
    mobile,
    emailaddress,
    civilstatus,
    height,
    weight,
    bmiresult,
    bmicategory,
    sssno,
    phno,
    tin,
    vip,
    reapply,
    rts,
    billingprovince,
    payorname,
    employer,
    occupation,
    industry,
    cardreleased,
    homeprovince,
    officeprovince,
    officephone,
    officefax,
    billto,
    zipcodehome,
    zipcodeoffice,
    zipcodebilling,
    billingcity,
    homecity,
    officecity,
    department,
    billingstreet,
    homestreet,
    officestreet,
    ineligible,
    dateineligible,
    renewalplancode,
    medicalremarks,
    bloodtype,
    nationality,
    datehired,
    migrated,
    rowmarker,
    allergies,
    otherhmo,
    deathdate,
    contactperson,
    contactnumber,
    accommodatedby,
    applicationo,
    remarks,
    withph,
    waiver,
    vessel,
    payortin,
    businessstyle,
    provideraccess,
    providerappservices,
    providerappservicesitems,
    pecwaived,
    dental,
    religion,
    withtelemedicine,
    newoccupation,
    monthlyfamilyincome,
    dummymemberno,
    grpprovideraccess,
    grpproviderallowed,
    grpprovidereffectivity,
    parentcompcode,
    pedcovered,
    peddays,
    paymentmethod,
    paymentmethoddetail,
    bankaccttype,
    bankacctno,
    center,
    accountofficer,
    unitmanager,
    province,
    municipality,
    barangay,
    street,
    modeofpayment,
    clienttype,
    repfirstname,
    repminame,
    replastname,
    reprelationship,
    returnstublink,
    placeofbirth,
    last_update_date
FROM
    adw_prod_tgt.TEMP_TBLMEMBERDETAILS;

COMMIT;

EXECUTE IMMEDIATE 'TRUNCATE TABLE adw_prod_tgt.TEMP_TBLMEMBERDETAILS';

--adw_prod_tgt.sp_adw_table_logs('TBLMEMBERDETAILS', 'SP_TEMP_MHI_TBLMEMBERDETAILS', SYSDATE, SYSDATE, 'UPDATE'); 


--transfer history 
--adw_prod_tgt.sp_adw_table_logs('TBLMEMBERDETAILS_HIST', 'SP_TEMP_MHI_TBLMEMBERDETAILS', SYSDATE, '', 'INSERT');
INSERT INTO --added by francis 05272025
    adw_prod_tgt.tblmemberdetails_hist (
        detno,
        compcode,
        membercode,
        memberno,
        importedcode,
        membertype,
        applicationno,
        picturename,
        birthplace,
        telephone,
        mobile,
        emailaddress,
        civilstatus,
        height,
        weight,
        bmiresult,
        bmicategory,
        sssno,
        phno,
        tin,
        vip,
        reapply,
        rts,
        billingprovince,
        payorname,
        employer,
        occupation,
        industry,
        cardreleased,
        homeprovince,
        officeprovince,
        officephone,
        officefax,
        billto,
        zipcodehome,
        zipcodeoffice,
        zipcodebilling,
        billingcity,
        homecity,
        officecity,
        department,
        billingstreet,
        homestreet,
        officestreet,
        ineligible,
        dateineligible,
        renewalplancode,
        medicalremarks,
        bloodtype,
        nationality,
        datehired,
        migrated,
        rowmarker,
        allergies,
        otherhmo,
        deathdate,
        contactperson,
        contactnumber,
        accommodatedby,
        applicationo,
        remarks,
        withph,
        waiver,
        vessel,
        payortin,
        businessstyle,
        provideraccess,
        providerappservices,
        providerappservicesitems,
        pecwaived,
        dental,
        religion,
        withtelemedicine,
        newoccupation,
        monthlyfamilyincome,
        dummymemberno,
        grpprovideraccess,
        grpproviderallowed,
        grpprovidereffectivity,
        parentcompcode,
        pedcovered,
        peddays,
        paymentmethod,
        paymentmethoddetail,
        bankaccttype,
        bankacctno,
        center,
        accountofficer,
        unitmanager,
        province,
        municipality,
        barangay,
        street,
        modeofpayment,
        clienttype,
        repfirstname,
        repminame,
        replastname,
        reprelationship,
        returnstublink,
        placeofbirth,
        last_update_date
    )
SELECT
    detno,
    compcode,
    membercode,
    memberno,
    importedcode,
    membertype,
    applicationno,
    picturename,
    birthplace,
    telephone,
    mobile,
    emailaddress,
    civilstatus,
    height,
    weight,
    bmiresult,
    bmicategory,
    sssno,
    phno,
    tin,
    vip,
    reapply,
    rts,
    billingprovince,
    payorname,
    employer,
    occupation,
    industry,
    cardreleased,
    homeprovince,
    officeprovince,
    officephone,
    officefax,
    billto,
    zipcodehome,
    zipcodeoffice,
    zipcodebilling,
    billingcity,
    homecity,
    officecity,
    department,
    billingstreet,
    homestreet,
    officestreet,
    ineligible,
    dateineligible,
    renewalplancode,
    medicalremarks,
    bloodtype,
    nationality,
    datehired,
    migrated,
    rowmarker,
    allergies,
    otherhmo,
    deathdate,
    contactperson,
    contactnumber,
    accommodatedby,
    applicationo,
    remarks,
    withph,
    waiver,
    vessel,
    payortin,
    businessstyle,
    provideraccess,
    providerappservices,
    providerappservicesitems,
    pecwaived,
    dental,
    religion,
    withtelemedicine,
    newoccupation,
    monthlyfamilyincome,
    dummymemberno,
    grpprovideraccess,
    grpproviderallowed,
    grpprovidereffectivity,
    parentcompcode,
    pedcovered,
    peddays,
    paymentmethod,
    paymentmethoddetail,
    bankaccttype,
    bankacctno,
    center,
    accountofficer,
    unitmanager,
    province,
    municipality,
    barangay,
    street,
    modeofpayment,
    clienttype,
    repfirstname,
    repminame,
    replastname,
    reprelationship,
    returnstublink,
    placeofbirth,
    last_update_date
FROM
    (
        SELECT
            detno,
            compcode,
            membercode,
            memberno,
            importedcode,
            membertype,
            applicationno,
            picturename,
            birthplace,
            telephone,
            mobile,
            emailaddress,
            civilstatus,
            height,
            weight,
            bmiresult,
            bmicategory,
            sssno,
            phno,
            tin,
            vip,
            reapply,
            rts,
            billingprovince,
            payorname,
            employer,
            occupation,
            industry,
            cardreleased,
            homeprovince,
            officeprovince,
            officephone,
            officefax,
            billto,
            zipcodehome,
            zipcodeoffice,
            zipcodebilling,
            billingcity,
            homecity,
            officecity,
            department,
            billingstreet,
            homestreet,
            officestreet,
            ineligible,
            dateineligible,
            renewalplancode,
            medicalremarks,
            bloodtype,
            nationality,
            datehired,
            migrated,
            rowmarker,
            allergies,
            otherhmo,
            deathdate,
            contactperson,
            contactnumber,
            accommodatedby,
            applicationo,
            remarks,
            withph,
            waiver,
            vessel,
            payortin,
            businessstyle,
            provideraccess,
            providerappservices,
            providerappservicesitems,
            pecwaived,
            dental,
            religion,
            withtelemedicine,
            newoccupation,
            monthlyfamilyincome,
            dummymemberno,
            grpprovideraccess,
            grpproviderallowed,
            grpprovidereffectivity,
            parentcompcode,
            pedcovered,
            peddays,
            paymentmethod,
            paymentmethoddetail,
            bankaccttype,
            bankacctno,
            center,
            accountofficer,
            unitmanager,
            province,
            municipality,
            barangay,
            street,
            modeofpayment,
            clienttype,
            repfirstname,
            repminame,
            replastname,
            reprelationship,
            returnstublink,
            placeofbirth,
            last_update_date,
            ROW_NUMBER() OVER (
                PARTITION BY
                    membercode
                ORDER BY
                    CASE
                        WHEN last_update_date IS NULL THEN 1
                        ELSE 0
                    END,
                    last_update_date desc
            ) AS Row_Num
        FROM
            adw_prod_tgt.TBLMEMBERDETAILS
        WHERE
            membercode IN (
                SELECT
                    membercode
                FROM
                    TBLMEMBERDETAILS
                GROUP BY
                    membercode
                HAVING
                    COUNT(*) > 1
            )
    )
WHERE
    Row_Num > 1;

COMMIT;

DELETE FROM adw_prod_tgt.TBLMEMBERDETAILS --added by francis 05272025
WHERE
    ROWID IN (
        SELECT
            ROWID
        FROM
            (
                SELECT
                    ROWID,
                    ROW_NUMBER() OVER (
                        PARTITION BY
                            membercode
                        ORDER BY
                            CASE
                                WHEN last_update_date IS NULL THEN 1
                                ELSE 0
                            END,
                            last_update_date DESC
                    ) AS Row_Num
                FROM
                    adw_prod_tgt.TBLMEMBERDETAILS
            )
        WHERE
            Row_Num > 1
    );

COMMIT;

-- --adw_prod_tgt.sp_adw_table_logs('TBLMEMBERDETAILS_HIST', 'SP_TEMP_MHI_TBLMEMBERDETAILS', SYSDATE, SYSDATE, 'UPDATE');

 
 END SP_TEMP_MHI_TBLMEMBERDETAILS;
 