create
or replace PROCEDURE SP_TEMP_MHI_TBLAGENTS AS BEGIN
/******************************************************************************

NAME:       SP_TEMP_MHI_TBLAGENTS
PURPOSE:   temp table to target

REVISIONS:
Ver          Date                  Author             Description
---------  ----------          ---------------  ------------------------------------
1.0        05/29/2025       Francis          1. Create SP_TEMP_MHI_TBLAGENTS


NOTES:

 ******************************************************************************/
 
--adw_prod_tgt.sp_adw_table_logs('TBLAGENTS', 'SP_TEMP_MHI_TBLAGENTS', SYSDATE, '', 'DELETE');
DELETE FROM adw_prod_tgt.TBLAGENTS
WHERE
    1 = 1
    AND TRUNC (dateencoded) >= TRUNC (SYSDATE);
COMMIT;
--adw_prod_tgt.sp_adw_table_logs('TBLAGENTS', 'SP_TEMP_MHI_TBLAGENTS', SYSDATE, '', 'INSERT');
INSERT INTO
    adw_prod_tgt.TBLAGENTS (
        agentno,
        agentcode,
        firstname,
        miname,
        lastname,
        suffix,
        agentname,
        birthdate,
        gender,
        civilstatus,
        agentclass,
        organization,
        status,
        effectivity,
        expiry,
        streetaddress,
        citycode,
        provincecode,
        divisioncode,
        branchno,
        branchcode,
        subbranchno,
        subbranchunitno,
        zipcode,
        vat,
        vattype,
        tinno,
        sssno,
        telephone,
        mobile,
        fax,
        emailaddress,
        bankacctno,
        bankno,
        banksaacct,
        bankbranch,
        bankacctname,
        wtax,
        encodedby,
        dateencoded,
        lastupdated,
        dateterminated,
        rowmarker,
        wtaxno,
        businesstyle,
        contactperson,
        contactdesignation,
        contactdepartment,
        codesuffix,
        regioncode,
        website,
        homephone,
        sourceaddress,
        sourcecity,
        sourceprovince,
        sourcezip,
        sourcephone,
        sourcefax,
        sourceweb,
        sourceexecutive,
        organizationno,
        honorifics,
        designation,
        department,
        fliagent,
        contactfax,
        contactmobile,
        contacthome,
        contactoffice,
        contactemail,
        clienttype,
        organizationtype,
        agenttype,
        agentlevel,
        statuscode,
        gsmno,
        usmno,
        organizationname,
        licenseno,
        rescertno,
        rescertplace,
        rescertdate,
        secno,
        dtino,
        dateactivated,
        datedeactivated,
        datedeceased,
        permanentaddress,
        permanentcitycode,
        permanentprovincecode,
        permanentzipcode,
        citizenship,
        birthplace,
        deviceid,
        devicebrand,
        devicemodel,
        deviceandroidversion,
        deviceram
    )
SELECT
    agentno,
    agentcode,
    firstname,
    miname,
    lastname,
    suffix,
    agentname,
    birthdate,
    gender,
    civilstatus,
    agentclass,
    organization,
    status,
    effectivity,
    expiry,
    streetaddress,
    citycode,
    provincecode,
    divisioncode,
    branchno,
    branchcode,
    subbranchno,
    subbranchunitno,
    zipcode,
    vat,
    vattype,
    tinno,
    sssno,
    telephone,
    mobile,
    fax,
    emailaddress,
    bankacctno,
    bankno,
    banksaacct,
    bankbranch,
    bankacctname,
    wtax,
    encodedby,
    dateencoded,
    lastupdated,
    dateterminated,
    rowmarker,
    wtaxno,
    businesstyle,
    contactperson,
    contactdesignation,
    contactdepartment,
    codesuffix,
    regioncode,
    website,
    homephone,
    sourceaddress,
    sourcecity,
    sourceprovince,
    sourcezip,
    sourcephone,
    sourcefax,
    sourceweb,
    sourceexecutive,
    organizationno,
    honorifics,
    designation,
    department,
    fliagent,
    contactfax,
    contactmobile,
    contacthome,
    contactoffice,
    contactemail,
    clienttype,
    organizationtype,
    agenttype,
    agentlevel,
    statuscode,
    gsmno,
    usmno,
    organizationname,
    licenseno,
    rescertno,
    rescertplace,
    rescertdate,
    secno,
    dtino,
    dateactivated,
    datedeactivated,
    datedeceased,
    permanentaddress,
    permanentcitycode,
    permanentprovincecode,
    permanentzipcode,
    citizenship,
    birthplace,
    deviceid,
    devicebrand,
    devicemodel,
    deviceandroidversion,
    deviceram
FROM
    adw_prod_tgt.TEMP_TBLAGENTS;
COMMIT;
EXECUTE IMMEDIATE 'TRUNCATE TABLE adw_prod_tgt.TEMP_TBLAGENTS';
--adw_prod_tgt.sp_adw_table_logs('TBLAGENTS', 'SP_TEMP_MHI_TBLAGENTS', SYSDATE, SYSDATE, 'UPDATE');

 
 END SP_TEMP_MHI_TBLAGENTS;
 