create
or replace PROCEDURE SP_TEMP_MHI_TBLACCTENTRIESCV AS BEGIN
/******************************************************************************

NAME:       SP_TEMP_MHI_TBLACCTENTRIESCV
PURPOSE:   temp table to target

REVISIONS:
Ver          Date                  Author             Description
---------  ----------          ---------------  ------------------------------------
1.0        05/29/2025       Francis          1. Create SP_TEMP_MHI_TBLACCTENTRIESCV


NOTES:

 ******************************************************************************/
 
--adw_prod_tgt.sp_adw_table_logs('TBLACCTENTRIESCV', 'SP_TEMP_MHI_TBLACCTENTRIESCV', SYSDATE, '', 'DELETE');
DELETE FROM adw_prod_tgt.TBLACCTENTRIESCV
WHERE 1=1
AND TRUNC(datecreated) >= TRUNC(SYSDATE);
COMMIT;
--adw_prod_tgt.sp_adw_table_logs('TBLACCTENTRIESCV', 'SP_TEMP_MHI_TBLACCTENTRIESCV', SYSDATE, '', 'INSERT');
INSERT INTO adw_prod_tgt.TBLACCTENTRIESCV (
trancode,
dvno,
billno,
voucherno,
voucherdate,
duedate,
acctname,
streetaddress,
provincecode,
citycode,
tinno,
vat,
wtaxrate,
wtaxamount,
organization,
acctcode,
providercode,
paytype,
particulars,
bankno,
checkamount,
tranamount,
discount,
exchangerate,
vatamount,
statuscode,
checkno,
checkdate,
checkdue,
datecreated,
branchno,
preparedby,
approvedby,
checkedby,
datereleased,
releasedby,
confidential,
sysgenerated,
taggedcheck,
referenceno,
userbranchno,
memocode,
rowmarker,
unccamount,
remarks,
accttype,
bankbranch,
bankaccount,
datecancelled,
controlno,
transmittalno,
wtaxno,
issueno,
claimcode,
membercode,
orno,
ordate,
slcode,
prinemployeeno,
basicclaim,
eobamount,
compcode,
dvdate,
dvtype,
jvno,
dvamount,
outside,
closedby,
pettycash,
agentno,
doctorcode,
membertype,
closedno,
dateclosed,
variousaddress,
varioustinno,
variouswtaxno,
wtaxsourceamount,
workstation,
paymenttype,
checkstatus,
paymentmethod,
paymentmethoddetail,
bankaccttype,
bankacctno,
recondate
)
SELECT
trancode,
dvno,
billno,
voucherno,
voucherdate,
duedate,
acctname,
streetaddress,
provincecode,
citycode,
tinno,
vat,
wtaxrate,
wtaxamount,
organization,
acctcode,
providercode,
paytype,
particulars,
bankno,
checkamount,
tranamount,
discount,
exchangerate,
vatamount,
statuscode,
checkno,
checkdate,
checkdue,
datecreated,
branchno,
preparedby,
approvedby,
checkedby,
datereleased,
releasedby,
confidential,
sysgenerated,
taggedcheck,
referenceno,
userbranchno,
memocode,
rowmarker,
unccamount,
remarks,
accttype,
bankbranch,
bankaccount,
datecancelled,
controlno,
transmittalno,
wtaxno,
issueno,
claimcode,
membercode,
orno,
ordate,
slcode,
prinemployeeno,
basicclaim,
eobamount,
compcode,
dvdate,
dvtype,
jvno,
dvamount,
outside,
closedby,
pettycash,
agentno,
doctorcode,
membertype,
closedno,
dateclosed,
variousaddress,
varioustinno,
variouswtaxno,
wtaxsourceamount,
workstation,
paymenttype,
checkstatus,
paymentmethod,
paymentmethoddetail,
bankaccttype,
bankacctno,
recondate
FROM adw_prod_tgt.TEMP_TBLACCTENTRIESCV;
COMMIT;
EXECUTE IMMEDIATE 'TRUNCATE TABLE adw_prod_tgt.TEMP_TBLACCTENTRIESCV';
--adw_prod_tgt.sp_adw_table_logs('TBLACCTENTRIESCV', 'SP_TEMP_MHI_TBLACCTENTRIESCV', SYSDATE, SYSDATE, 'UPDATE');
 
 END SP_TEMP_MHI_TBLACCTENTRIESCV;
 