CREATE
OR
ALTER PROCEDURE dbo.sp_decrypt_micro_hmo_il AS BEGIN
/******************************************************************************

NAME:       sp_decrypt_micro_hmo_il
PURPOSE:    transfer decrypted data to temp table 

REVISIONS:
Ver          Date                  Author             Description
---------  ----------          ---------------  ------------------------------------
1.0        05/16/2025       Francis          1. Create sp_decrypt_micro_hmo_il
2.0        05/19/2025       Francis          1. add dpt_tblsoapremiummembers
2.1        05/23/2025       Francis          1. add update data of tblclaims whenever there is data need to be updated
2.2        05/27/2025       Francis          1. added last_update_date column in tblmembers and tblmemberdetails
2.3        05/27/2025       Francis          1. added dpt_tblloas    
2.4        05/28/2025       Francis          1. added dpt_tbldoctorspecialization


NOTES:

 ******************************************************************************/
BEGIN TRANSACTION;

BEGIN TRY
-- Open the symmetric key
EXEC hmspioneer.dbo.sp_opensymmetric;

-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblclaims
WHERE
    1 = 1
    AND CAST(dateencoded AS DATE) >= CAST(GETDATE () AS DATE);

-- --add by francis 05232025 update the tblclaims data -- remove 05262025
-- MERGE INTO stg_hmspioneer.dbo.dpt_tblclaims AS tgt USING (
--     SELECT
--         claimcode,
--         caseno,
--         casetype,
--         claimreceived,
--         claimstatus,
--         claimtype,
--         subclaimtype,
--         dateclosed,
--         compcode,
--         hmspioneer.dbo.decrypt (companyname) AS companyname,
--         companystatus,
--         membercode,
--         memberno,
--         hmspioneer.dbo.decrypt (membername) AS membername,
--         membertype,
--         membercategory,
--         levelcode,
--         memberstatus,
--         principalcode,
--         hmspioneer.dbo.decrypt (principalname) AS principalname,
--         principalno,
--         oldplancode,
--         planname,
--         coveredfrom,
--         coveredto,
--         birthdate,
--         gender,
--         classorder,
--         origeffectivity,
--         policydivision,
--         sharedplan,
--         providercode,
--         dateavailed,
--         datedischarged,
--         eligibilitystatus,
--         loano,
--         loaamount,
--         loadateapproved,
--         loaapprovedby,
--         manualloano,
--         manualloadateapproved,
--         manualloaamount,
--         finalamount,
--         provideramount,
--         pfamount,
--         reamount,
--         roomamount,
--         phamount,
--         discount,
--         adjamount,
--         eobamount,
--         adjamountpf,
--         incrementalcharges,
--         incrementalamount,
--         pfdiscount,
--         claimshandlingfee,
--         claimshandlingamount,
--         finalreamount,
--         nppfamount,
--         npamount,
--         refundamountpf,
--         phpfamount,
--         rerate,
--         refundamount,
--         duetomember,
--         creditedamount,
--         remarks,
--         claims,
--         claimsprocessor,
--         roomtype,
--         accredited,
--         importedcode,
--         jvnoap,
--         eobno,
--         basicclaim,
--         majorclaim,
--         spilloverclaim,
--         origbasicclaim,
--         origmajorclaim,
--         origspilloverclaim,
--         billno,
--         intervininggroup,
--         icdno,
--         dvno,
--         dateencoded,
--         encodedby,
--         rowmarker,
--         asoadminfeetype,
--         asoservicefeetype,
--         asoservicefee,
--         asosoano,
--         provideraccess,
--         casereceived,
--         casestatus,
--         contractno,
--         relatedplangroup,
--         benefitclass,
--         plancode,
--         operatorcode,
--         eobtolerance,
--         seen,
--         hbadjdisapproved,
--         pfadjdisapproved,
--         hbadjapproved,
--         pfadjapproved,
--         clienttype,
--         homestreet,
--         homecity,
--         homeprovince,
--         zipcodehome,
--         occupation,
--         datedenied,
--         denialreason,
--         branchno
--     FROM
--         hmspioneer.dbo.tblclaims
--     WHERE
--         caseno IN (
--             SELECT
--                 c.caseno
--             FROM
--                 hmspioneer.dbo.tblclaims c
--             WHERE
--                 (
--                     SELECT
--                         MAX(cp.dateposted)
--                     FROM
--                         hmspioneer.dbo.tblclaimprogress cp
--                     WHERE
--                         cp.claimcode = c.claimcode
--                 ) >= CAST(GETDATE () - 1 AS DATE) --change here if you want to change the date 
--         )
-- ) AS src ON tgt.caseno = src.caseno WHEN MATCHED THEN
-- UPDATE
-- SET
--     tgt.claimcode = src.claimcode,
--     tgt.casetype = src.casetype,
--     tgt.claimreceived = src.claimreceived,
--     tgt.claimstatus = src.claimstatus,
--     tgt.claimtype = src.claimtype,
--     tgt.subclaimtype = src.subclaimtype,
--     tgt.dateclosed = src.dateclosed,
--     tgt.compcode = src.compcode,
--     tgt.companyname = src.companyname,
--     tgt.companystatus = src.companystatus,
--     tgt.membercode = src.membercode,
--     tgt.memberno = src.memberno,
--     tgt.membername = src.membername,
--     tgt.membertype = src.membertype,
--     tgt.membercategory = src.membercategory,
--     tgt.levelcode = src.levelcode,
--     tgt.memberstatus = src.memberstatus,
--     tgt.principalcode = src.principalcode,
--     tgt.principalname = src.principalname,
--     tgt.principalno = src.principalno,
--     tgt.oldplancode = src.oldplancode,
--     tgt.planname = src.planname,
--     tgt.coveredfrom = src.coveredfrom,
--     tgt.coveredto = src.coveredto,
--     tgt.birthdate = src.birthdate,
--     tgt.gender = src.gender,
--     tgt.classorder = src.classorder,
--     tgt.origeffectivity = src.origeffectivity,
--     tgt.policydivision = src.policydivision,
--     tgt.sharedplan = src.sharedplan,
--     tgt.providercode = src.providercode,
--     tgt.dateavailed = src.dateavailed,
--     tgt.datedischarged = src.datedischarged,
--     tgt.eligibilitystatus = src.eligibilitystatus,
--     tgt.loano = src.loano,
--     tgt.loaamount = src.loaamount,
--     tgt.loadateapproved = src.loadateapproved,
--     tgt.loaapprovedby = src.loaapprovedby,
--     tgt.manualloano = src.manualloano,
--     tgt.manualloadateapproved = src.manualloadateapproved,
--     tgt.manualloaamount = src.manualloaamount,
--     tgt.finalamount = src.finalamount,
--     tgt.provideramount = src.provideramount,
--     tgt.pfamount = src.pfamount,
--     tgt.reamount = src.reamount,
--     tgt.roomamount = src.roomamount,
--     tgt.phamount = src.phamount,
--     tgt.discount = src.discount,
--     tgt.adjamount = src.adjamount,
--     tgt.eobamount = src.eobamount,
--     tgt.adjamountpf = src.adjamountpf,
--     tgt.incrementalcharges = src.incrementalcharges,
--     tgt.incrementalamount = src.incrementalamount,
--     tgt.pfdiscount = src.pfdiscount,
--     tgt.claimshandlingfee = src.claimshandlingfee,
--     tgt.claimshandlingamount = src.claimshandlingamount,
--     tgt.finalreamount = src.finalreamount,
--     tgt.nppfamount = src.nppfamount,
--     tgt.npamount = src.npamount,
--     tgt.refundamountpf = src.refundamountpf,
--     tgt.phpfamount = src.phpfamount,
--     tgt.rerate = src.rerate,
--     tgt.refundamount = src.refundamount,
--     tgt.duetomember = src.duetomember,
--     tgt.creditedamount = src.creditedamount,
--     tgt.remarks = src.remarks,
--     tgt.claims = src.claims,
--     tgt.claimsprocessor = src.claimsprocessor,
--     tgt.roomtype = src.roomtype,
--     tgt.accredited = src.accredited,
--     tgt.importedcode = src.importedcode,
--     tgt.jvnoap = src.jvnoap,
--     tgt.eobno = src.eobno,
--     tgt.basicclaim = src.basicclaim,
--     tgt.majorclaim = src.majorclaim,
--     tgt.spilloverclaim = src.spilloverclaim,
--     tgt.origbasicclaim = src.origbasicclaim,
--     tgt.origmajorclaim = src.origmajorclaim,
--     tgt.origspilloverclaim = src.origspilloverclaim,
--     tgt.billno = src.billno,
--     tgt.intervininggroup = src.intervininggroup,
--     tgt.icdno = src.icdno,
--     tgt.dvno = src.dvno,
--     tgt.dateencoded = src.dateencoded,
--     tgt.encodedby = src.encodedby,
--     tgt.rowmarker = src.rowmarker,
--     tgt.asoadminfeetype = src.asoadminfeetype,
--     tgt.asoservicefeetype = src.asoservicefeetype,
--     tgt.asoservicefee = src.asoservicefee,
--     tgt.asosoano = src.asosoano,
--     tgt.provideraccess = src.provideraccess,
--     tgt.casereceived = src.casereceived,
--     tgt.casestatus = src.casestatus,
--     tgt.contractno = src.contractno,
--     tgt.relatedplangroup = src.relatedplangroup,
--     tgt.benefitclass = src.benefitclass,
--     tgt.plancode = src.plancode,
--     tgt.operatorcode = src.operatorcode,
--     tgt.eobtolerance = src.eobtolerance,
--     tgt.seen = src.seen,
--     tgt.hbadjdisapproved = src.hbadjdisapproved,
--     tgt.pfadjdisapproved = src.pfadjdisapproved,
--     tgt.hbadjapproved = src.hbadjapproved,
--     tgt.pfadjapproved = src.pfadjapproved,
--     tgt.clienttype = src.clienttype,
--     tgt.homestreet = src.homestreet,
--     tgt.homecity = src.homecity,
--     tgt.homeprovince = src.homeprovince,
--     tgt.zipcodehome = src.zipcodehome,
--     tgt.occupation = src.occupation,
--     tgt.datedenied = src.datedenied,
--     tgt.denialreason = src.denialreason,
--     tgt.branchno = src.branchno;
-- Insert data into `dpt_tblclaims`
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblclaims (
        claimcode,
        caseno,
        casetype,
        claimreceived,
        claimstatus,
        claimtype,
        subclaimtype,
        dateclosed,
        compcode,
        companyname,
        companystatus,
        membercode,
        memberno,
        membername,
        membertype,
        membercategory,
        levelcode,
        memberstatus,
        principalcode,
        principalname,
        principalno,
        oldplancode,
        planname,
        coveredfrom,
        coveredto,
        birthdate,
        gender,
        classorder,
        origeffectivity,
        policydivision,
        sharedplan,
        providercode,
        dateavailed,
        datedischarged,
        eligibilitystatus,
        loano,
        loaamount,
        loadateapproved,
        loaapprovedby,
        manualloano,
        manualloadateapproved,
        manualloaamount,
        finalamount,
        provideramount,
        pfamount,
        reamount,
        roomamount,
        phamount,
        discount,
        adjamount,
        eobamount,
        adjamountpf,
        incrementalcharges,
        incrementalamount,
        pfdiscount,
        claimshandlingfee,
        claimshandlingamount,
        finalreamount,
        nppfamount,
        npamount,
        refundamountpf,
        phpfamount,
        rerate,
        refundamount,
        duetomember,
        creditedamount,
        remarks,
        claims,
        claimsprocessor,
        roomtype,
        accredited,
        importedcode,
        jvnoap,
        eobno,
        basicclaim,
        majorclaim,
        spilloverclaim,
        origbasicclaim,
        origmajorclaim,
        origspilloverclaim,
        billno,
        intervininggroup,
        icdno,
        dvno,
        dateencoded,
        encodedby,
        rowmarker,
        asoadminfeetype,
        asoservicefeetype,
        asoservicefee,
        asosoano,
        provideraccess,
        casereceived,
        casestatus,
        contractno,
        relatedplangroup,
        benefitclass,
        plancode,
        operatorcode,
        eobtolerance,
        seen,
        hbadjdisapproved,
        pfadjdisapproved,
        hbadjapproved,
        pfadjapproved,
        clienttype,
        homestreet,
        homecity,
        homeprovince,
        zipcodehome,
        occupation,
        datedenied,
        denialreason,
        branchno,
        dateposted
    )
SELECT
    c.claimcode,
    c.caseno,
    c.casetype,
    c.claimreceived,
    c.claimstatus,
    c.claimtype,
    c.subclaimtype,
    c.dateclosed,
    c.compcode,
    hmspioneer.dbo.decrypt (c.companyname) AS companyname,
    c.companystatus,
    c.membercode,
    c.memberno,
    hmspioneer.dbo.decrypt (c.membername) AS membername,
    c.membertype,
    c.membercategory,
    c.levelcode,
    c.memberstatus,
    c.principalcode,
    hmspioneer.dbo.decrypt (c.principalname) AS principalname,
    c.principalno,
    c.oldplancode,
    c.planname,
    c.coveredfrom,
    c.coveredto,
    c.birthdate,
    c.gender,
    c.classorder,
    c.origeffectivity,
    c.policydivision,
    c.sharedplan,
    c.providercode,
    c.dateavailed,
    c.datedischarged,
    c.eligibilitystatus,
    c.loano,
    c.loaamount,
    c.loadateapproved,
    c.loaapprovedby,
    c.manualloano,
    c.manualloadateapproved,
    c.manualloaamount,
    c.finalamount,
    c.provideramount,
    c.pfamount,
    c.reamount,
    c.roomamount,
    c.phamount,
    c.discount,
    c.adjamount,
    c.eobamount,
    c.adjamountpf,
    c.incrementalcharges,
    c.incrementalamount,
    c.pfdiscount,
    c.claimshandlingfee,
    c.claimshandlingamount,
    c.finalreamount,
    c.nppfamount,
    c.npamount,
    c.refundamountpf,
    c.phpfamount,
    c.rerate,
    c.refundamount,
    c.duetomember,
    c.creditedamount,
    c.remarks,
    c.claims,
    c.claimsprocessor,
    c.roomtype,
    c.accredited,
    c.importedcode,
    c.jvnoap,
    c.eobno,
    c.basicclaim,
    c.majorclaim,
    c.spilloverclaim,
    c.origbasicclaim,
    c.origmajorclaim,
    c.origspilloverclaim,
    c.billno,
    c.intervininggroup,
    c.icdno,
    c.dvno,
    c.dateencoded,
    c.encodedby,
    c.rowmarker,
    c.asoadminfeetype,
    c.asoservicefeetype,
    c.asoservicefee,
    c.asosoano,
    c.provideraccess,
    c.casereceived,
    c.casestatus,
    c.contractno,
    c.relatedplangroup,
    c.benefitclass,
    c.plancode,
    c.operatorcode,
    c.eobtolerance,
    c.seen,
    c.hbadjdisapproved,
    c.pfadjdisapproved,
    c.hbadjapproved,
    c.pfadjapproved,
    c.clienttype,
    c.homestreet,
    c.homecity,
    c.homeprovince,
    c.zipcodehome,
    c.occupation,
    c.datedenied,
    c.denialreason,
    c.branchno,
    ISNULL (
        (
            SELECT
                MAX(cp.dateposted)
            FROM
                hmspioneer.dbo.tblclaimprogress cp
            WHERE
                cp.claimcode = c.claimcode
        ),
        c.dateencoded
    ) AS dateposted
FROM
    hmspioneer.dbo.tblclaims c
WHERE
    1 = 1
    AND CAST(c.dateencoded AS DATE) = CAST(GETDATE () - 1 AS DATE) --NEW
    OR (
        SELECT
            CAST(MAX(cp.dateposted) AS DATE)
        FROM
            hmspioneer.dbo.tblclaimprogress cp
        WHERE
            cp.claimcode = c.claimcode
    ) = CAST(GETDATE () - 1 AS DATE);

-- EXISTING
----------------------------------------------1------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblcompany
where
    1 = 1
    AND CAST(dateencoded AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into `dpt_tblcompany`
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblcompany (
        compcode,
        contractno,
        manualcontractno,
        companyname,
        companytype,
        companysetup,
        productcode,
        initial,
        dtino,
        secno,
        tinno,
        vattype,
        telephone,
        fax,
        website,
        dateenrolled,
        effectivity,
        expiry,
        coveredfrom,
        coveredto,
        paiddate,
        inactivedate,
        statuscode,
        renewal,
        reactivationdate,
        sendbillingto,
        billingcompcode,
        billingschedule,
        streetaddress,
        citycode,
        provincecode,
        regionno,
        parentcompcode,
        renewaleffectivity,
        renewaldue,
        lastbilled,
        nextbilling,
        withrevolvingfund,
        revolvingfund,
        fundlimit,
        replenishmentamt,
        consumedamt,
        claimshandlingfee,
        guaranteedep,
        generatesoa,
        autore,
        owned,
        acctseries,
        compensationtype,
        compensationrate,
        billsubgroup,
        billingagentno,
        billduesetup,
        contactperson,
        wtax,
        wtaxno,
        ewt,
        vatsetup,
        billcount,
        policygroup,
        agentno,
        sourcecontact,
        encodedby,
        dateencoded,
        rowmarker,
        withguaranteedeposit,
        billbackeob,
        asoadditionalamt,
        asoadjustmentamt,
        iprate,
        ipamount,
        oprate,
        opamount,
        rerate,
        reamount,
        dcrate,
        dcamount,
        nafrate,
        nafamount,
        planctr,
        corporatelimit,
        familylimit,
        slcode,
        contractyears,
        aradminfee,
        vatablepercent,
        commissionrate,
        slagentno,
        withcwtax,
        migrated,
        ibnrvalidity,
        withbenefitpdf,
        notprorated,
        producttype,
        memberposition,
        longtermperiod,
        adminfee,
        asoremarks,
        premiumformula,
        currentaddressee,
        nolapsation,
        cwtax,
        topcompany,
        billingdays,
        restrictmobile,
        branch,
        accountcode,
        asoadminfeetype,
        asoadminfee,
        asoservicefeetype,
        asoservicefee,
        roundingoff,
        memberpremium,
        premiumcaption,
        separatebillprindep,
        creditterms,
        lineofbusiness,
        corporateno,
        franchiseno,
        branchno,
        divisioncode,
        gsmno,
        usmno,
        sano,
        brokerno,
        directno,
        memberportalaccessfrom,
        memberportalaccessto,
        allowmemberportal,
        memberportaldays,
        businesstyle,
        mribeneficiary,
        zipcode,
        lob,
        ldflog,
        incorpcountrycode,
        datesuspended,
        rebatebilling,
        allowmemberexceedyear,
        fullpaymentrate,
        autoextend,
        channel
    )
SELECT
    compcode,
    contractno,
    manualcontractno,
    hmspioneer.dbo.decrypt (companyname) AS companyname,
    companytype,
    companysetup,
    productcode,
    initial,
    dtino,
    secno,
    tinno,
    vattype,
    telephone,
    fax,
    website,
    dateenrolled,
    effectivity,
    expiry,
    coveredfrom,
    coveredto,
    paiddate,
    inactivedate,
    statuscode,
    renewal,
    reactivationdate,
    sendbillingto,
    billingcompcode,
    billingschedule,
    streetaddress,
    citycode,
    provincecode,
    regionno,
    parentcompcode,
    renewaleffectivity,
    renewaldue,
    lastbilled,
    nextbilling,
    withrevolvingfund,
    revolvingfund,
    fundlimit,
    replenishmentamt,
    consumedamt,
    claimshandlingfee,
    guaranteedep,
    generatesoa,
    autore,
    owned,
    acctseries,
    compensationtype,
    compensationrate,
    billsubgroup,
    billingagentno,
    billduesetup,
    contactperson,
    wtax,
    wtaxno,
    ewt,
    vatsetup,
    billcount,
    policygroup,
    agentno,
    sourcecontact,
    encodedby,
    dateencoded,
    rowmarker,
    withguaranteedeposit,
    billbackeob,
    asoadditionalamt,
    asoadjustmentamt,
    iprate,
    ipamount,
    oprate,
    opamount,
    rerate,
    reamount,
    dcrate,
    dcamount,
    nafrate,
    nafamount,
    planctr,
    corporatelimit,
    familylimit,
    slcode,
    contractyears,
    aradminfee,
    vatablepercent,
    commissionrate,
    slagentno,
    withcwtax,
    migrated,
    ibnrvalidity,
    withbenefitpdf,
    notprorated,
    producttype,
    memberposition,
    longtermperiod,
    adminfee,
    asoremarks,
    premiumformula,
    currentaddressee,
    nolapsation,
    cwtax,
    topcompany,
    billingdays,
    restrictmobile,
    branch,
    accountcode,
    asoadminfeetype,
    asoadminfee,
    asoservicefeetype,
    asoservicefee,
    roundingoff,
    memberpremium,
    premiumcaption,
    separatebillprindep,
    creditterms,
    lineofbusiness,
    corporateno,
    franchiseno,
    branchno,
    divisioncode,
    gsmno,
    usmno,
    sano,
    brokerno,
    directno,
    memberportalaccessfrom,
    memberportalaccessto,
    allowmemberportal,
    memberportaldays,
    businesstyle,
    mribeneficiary,
    zipcode,
    lob,
    ldflog,
    incorpcountrycode,
    datesuspended,
    rebatebilling,
    allowmemberexceedyear,
    fullpaymentrate,
    autoextend,
    channel
FROM
    hmspioneer.dbo.tblcompany
WHERE
    1 = 1
    AND CAST(dateencoded AS DATE) = CAST(GETDATE () -1 AS DATE);

----------------------------------------------2------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblmembers
WHERE
    1 = 1
    AND CAST(dateencoded AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into `dpt_tblmembers`
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblmembers (
        membercode,
        memberno,
        memberyear,
        membertype,
        firstname,
        miname,
        lastname,
        membername,
        suffix,
        gender,
        birthdate,
        classorder,
        principalcode,
        relation,
        compcode,
        plancode,
        prevplancode,
        premiumfee,
        extrarate,
        standardrate,
        originalfee,
        origeffectivity,
        inactivedate,
        effectivity,
        expiry,
        statuscode,
        billingschedule,
        coveredfrom,
        coveredto,
        employeeno,
        newinvoice,
        renewalplancode,
        plname,
        pfname,
        bmicategory,
        membercategory,
        levelcode,
        cardnumber,
        migrated,
        dateencoded,
        encodedby,
        importedcode,
        cardbatchno,
        groupno,
        groupcode,
        philhealth,
        renewal,
        newtrialno,
        canceltrialno,
        renewtrialno,
        cardtype,
        cardpec,
        nextbilling,
        rowmarker,
        policydivision,
        streetaddress,
        migrationno,
        agentno,
        slcode,
        relatecode,
        premiumamt,
        nafamt,
        dafamt,
        billed,
        phfee,
        dentalfee,
        applicationcode,
        producttype,
        lapsed,
        companysubgroup,
        premschemecode,
        depcount,
        lastbilledfrom,
        lastbilledto,
        civilstatus,
        branch,
        specialrate,
        paidfrom,
        paidto,
        credittermto,
        premiumincrease,
        premiumincreasetype,
        mdflog,
        llog,
        flog,
        pllog,
        pflog,
        benefitclass,
        parentcompcode,
        premiumclass,
        provincecode,
        zipcode,
        dummymemberno,
        citycode,
        retailupload,
        employeeshare,
        companyshare,
        jobsite,
        remittancedate,
        loanreleasedate,
        cardinstitution,
        microinsurancesupervisor,
        tellerbookkeeper,
        regionalmanager,
        orno,
        datepaid,
        membershipinstitutionno,
        accountbankbranchno,
        loanbankbranchno,
        last_update_date
    )
SELECT
    a.membercode,
    a.memberno,
    a.memberyear,
    a.membertype,
    hmspioneer.dbo.decrypt (a.firstname) as firstname,
    hmspioneer.dbo.decrypt (a.miname) as miname,
    hmspioneer.dbo.decrypt (a.lastname) as lastname,
    hmspioneer.dbo.decrypt (a.membername) as membername,
    a.suffix,
    a.gender,
    a.birthdate,
    a.classorder,
    a.principalcode,
    a.relation,
    a.compcode,
    a.plancode,
    a.prevplancode,
    a.premiumfee,
    a.extrarate,
    a.standardrate,
    a.originalfee,
    a.origeffectivity,
    a.inactivedate,
    a.effectivity,
    a.expiry,
    a.statuscode,
    a.billingschedule,
    a.coveredfrom,
    a.coveredto,
    a.employeeno,
    a.newinvoice,
    a.renewalplancode,
    a.plname,
    a.pfname,
    a.bmicategory,
    a.membercategory,
    a.levelcode,
    a.cardnumber,
    a.migrated,
    a.dateencoded,
    a.encodedby,
    a.importedcode,
    a.cardbatchno,
    a.groupno,
    a.groupcode,
    a.philhealth,
    a.renewal,
    a.newtrialno,
    a.canceltrialno,
    a.renewtrialno,
    a.cardtype,
    a.cardpec,
    a.nextbilling,
    a.rowmarker,
    a.policydivision,
    a.streetaddress,
    a.migrationno,
    a.agentno,
    a.slcode,
    a.relatecode,
    a.premiumamt,
    a.nafamt,
    a.dafamt,
    a.billed,
    a.phfee,
    a.dentalfee,
    a.applicationcode,
    a.producttype,
    a.lapsed,
    a.companysubgroup,
    a.premschemecode,
    a.depcount,
    a.lastbilledfrom,
    a.lastbilledto,
    a.civilstatus,
    a.branch,
    a.specialrate,
    a.paidfrom,
    a.paidto,
    a.credittermto,
    a.premiumincrease,
    a.premiumincreasetype,
    a.mdflog,
    a.llog,
    a.flog,
    a.pllog,
    a.pflog,
    a.benefitclass,
    a.parentcompcode,
    a.premiumclass,
    a.provincecode,
    a.zipcode,
    a.dummymemberno,
    a.citycode,
    a.retailupload,
    a.employeeshare,
    a.companyshare,
    a.jobsite,
    a.remittancedate,
    a.loanreleasedate,
    a.cardinstitution,
    a.microinsurancesupervisor,
    a.tellerbookkeeper,
    a.regionalmanager,
    a.orno,
    a.datepaid,
    a.membershipinstitutionno,
    a.accountbankbranchno,
    a.loanbankbranchno,
    ISNULL (
        (
            select
                max(b.dateencoded)
            from
                hmspioneer.dbo.tblmemberamendment b
            where
                b.membercode = a.membercode
        ),
        a.dateencoded
    ) as last_update_date
FROM
    hmspioneer.dbo.tblmembers a
WHERE
    1 = 1
    AND CAST(a.dateencoded AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(c.dateencoded) AS DATE)
        FROM
            hmspioneer.dbo.tblmemberamendment c
        WHERE
            c.membercode = a.membercode
    ) = CAST(GETDATE () - 1 AS DATE);

----------------------------------------------3------------------------------------------------------
-- Clear data from table
DELETE a
FROM
    stg_hmspioneer.dbo.dpt_tblmemberdetails a
    JOIN stg_hmspioneer.dbo.dpt_tblmembers b ON a.membercode = b.membercode
WHERE
    1 = 1
    AND CAST(b.dateencoded AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into dpt_tblmemberdetails
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblmemberdetails (
        detno,
        compcode,
        membercode,
        memberno,
        importedcode,
        membertype,
        applicationno,
        picturename,
        birthplace,
        telephone,
        mobile,
        emailaddress,
        civilstatus,
        height,
        weight,
        bmiresult,
        bmicategory,
        sssno,
        phno,
        tin,
        vip,
        reapply,
        rts,
        billingprovince,
        payorname,
        employer,
        occupation,
        industry,
        cardreleased,
        homeprovince,
        officeprovince,
        officephone,
        officefax,
        billto,
        zipcodehome,
        zipcodeoffice,
        zipcodebilling,
        billingcity,
        homecity,
        officecity,
        department,
        billingstreet,
        homestreet,
        officestreet,
        ineligible,
        dateineligible,
        renewalplancode,
        medicalremarks,
        bloodtype,
        nationality,
        datehired,
        migrated,
        rowmarker,
        allergies,
        otherhmo,
        deathdate,
        contactperson,
        contactnumber,
        accommodatedby,
        applicationo,
        remarks,
        withph,
        waiver,
        vessel,
        payortin,
        businessstyle,
        provideraccess,
        providerappservices,
        providerappservicesitems,
        pecwaived,
        dental,
        religion,
        withtelemedicine,
        newoccupation,
        monthlyfamilyincome,
        dummymemberno,
        grpprovideraccess,
        grpproviderallowed,
        grpprovidereffectivity,
        parentcompcode,
        pedcovered,
        peddays,
        paymentmethod,
        paymentmethoddetail,
        bankaccttype,
        bankacctno,
        center,
        accountofficer,
        unitmanager,
        province,
        municipality,
        barangay,
        street,
        modeofpayment,
        clienttype,
        repfirstname,
        repminame,
        replastname,
        reprelationship,
        placeofbirth,
        returnstublink,
        last_update_date
    )
SELECT
    a.detno,
    a.compcode,
    a.membercode,
    a.memberno,
    a.importedcode,
    a.membertype,
    a.applicationno,
    a.picturename,
    a.birthplace,
    a.telephone,
    hmspioneer.dbo.decrypt (a.mobile) AS mobile,
    hmspioneer.dbo.decrypt (a.emailaddress) AS emailaddress,
    a.civilstatus,
    a.height,
    a.weight,
    a.bmiresult,
    a.bmicategory,
    a.sssno,
    a.phno,
    a.tin,
    a.vip,
    a.reapply,
    a.rts,
    a.billingprovince,
    a.payorname,
    a.employer,
    a.occupation,
    a.industry,
    a.cardreleased,
    a.homeprovince,
    a.officeprovince,
    a.officephone,
    a.officefax,
    a.billto,
    a.zipcodehome,
    a.zipcodeoffice,
    a.zipcodebilling,
    a.billingcity,
    a.homecity,
    a.officecity,
    a.department,
    a.billingstreet,
    a.homestreet,
    a.officestreet,
    a.ineligible,
    a.dateineligible,
    a.renewalplancode,
    a.medicalremarks,
    a.bloodtype,
    a.nationality,
    a.datehired,
    a.migrated,
    a.rowmarker,
    a.allergies,
    a.otherhmo,
    a.deathdate,
    a.contactperson,
    a.contactnumber,
    a.accommodatedby,
    a.applicationo,
    a.remarks,
    a.withph,
    a.waiver,
    a.vessel,
    a.payortin,
    a.businessstyle,
    a.provideraccess,
    a.providerappservices,
    a.providerappservicesitems,
    a.pecwaived,
    a.dental,
    a.religion,
    a.withtelemedicine,
    a.newoccupation,
    a.monthlyfamilyincome,
    a.dummymemberno,
    a.grpprovideraccess,
    a.grpproviderallowed,
    a.grpprovidereffectivity,
    a.parentcompcode,
    a.pedcovered,
    a.peddays,
    a.paymentmethod,
    a.paymentmethoddetail,
    a.bankaccttype,
    a.bankacctno,
    a.center,
    a.accountofficer,
    a.unitmanager,
    a.province,
    a.municipality,
    a.barangay,
    a.street,
    a.modeofpayment,
    a.clienttype,
    a.repfirstname,
    a.repminame,
    a.replastname,
    a.reprelationship,
    a.placeofbirth,
    a.returnstublink,
    ISNULL (
        (
            select
                max(c.dateencoded)
            from
                hmspioneer.dbo.tblmemberamendment c
            where
                c.membercode = a.membercode
        ),
        b.dateencoded
    ) as last_update_date
FROM
    hmspioneer.dbo.tblmemberdetails a
    JOIN hmspioneer.dbo.tblmembers b ON a.membercode = b.membercode
WHERE
    1 = 1
    AND CAST(b.dateencoded AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(d.dateencoded) AS DATE)
        FROM
            hmspioneer.dbo.tblmemberamendment d
        WHERE
            d.membercode = a.membercode
    ) = CAST(GETDATE () - 1 AS DATE);

----------------------------------------------4------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblsoapremiummembers
WHERE
    1 = 1
    AND CAST(dateencoded AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into dpt_tblsoapremiummembers
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblsoapremiummembers (
        detno,
        soano,
        soacode,
        plancode,
        soasobdetno,
        memberpremium,
        premiumcode,
        compcode,
        membercode,
        memberno,
        membername,
        membercategory,
        classorder,
        sobamount,
        batchcode,
        batchtype,
        dateencoded,
        encodedby,
        effectivity,
        modalfrom,
        modalto,
        rowmarker,
        basepremium,
        policydivision,
        vatamount,
        feecode,
        additional,
        madamount,
        memberfeecode,
        premiumclass,
        paidamount
    )
select
    detno,
    soano,
    soacode,
    plancode,
    soasobdetno,
    memberpremium,
    premiumcode,
    compcode,
    membercode,
    memberno,
    hmspioneer.dbo.decrypt (membername) as membername,
    membercategory,
    classorder,
    sobamount,
    batchcode,
    batchtype,
    dateencoded,
    encodedby,
    effectivity,
    modalfrom,
    modalto,
    rowmarker,
    basepremium,
    policydivision,
    vatamount,
    feecode,
    additional,
    madamount,
    memberfeecode,
    premiumclass,
    paidamount
from
    hmspioneer.dbo.tblsoapremiummembers
WHERE
    1 = 1
    AND CAST(dateencoded AS DATE) = CAST(GETDATE () - 1 AS DATE);

----------------------------------------------5------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblloas
WHERE
    1 = 1
    AND CAST(dateencoded AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into dpt_tblloas
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblloas (
        loacode,
        loadate,
        loano,
        claimtype,
        subclaimtype,
        callername,
        callercontact,
        compcode,
        companyname,
        companystatus,
        membercode,
        memberno,
        membername,
        membertype,
        membercategory,
        levelcode,
        memberstatus,
        principalcode,
        principalname,
        principalno,
        classorder,
        policydivision,
        providercode,
        dateavailed,
        datedischarged,
        loastatus,
        eligibilitystatus,
        loaamount,
        dateapproved,
        datedue,
        approvedby,
        oldplancode,
        planname,
        roomtype,
        coveredfrom,
        coveredto,
        birthdate,
        gender,
        vip,
        origeffectivity,
        intervininggroup,
        creditedamount,
        sharedplan,
        admittingtext,
        doctorcode,
        doctorname,
        otherexclusions,
        procedures,
        icdno,
        remarks,
        dateencoded,
        encodedend,
        encodedby,
        encodedduration,
        rowmarker,
        loaconcerndesc,
        loaconcernno,
        loarequestcode,
        withguaranteeletter,
        controlno,
        philhealth,
        miscrnb,
        miscrnbamount,
        miscancillary,
        miscancillaryamount,
        miscproffee,
        miscproffeeamount,
        miscmbl,
        miscmblamount,
        misctakehome,
        misctakehomeamount,
        miscothers,
        miscothersamount,
        misccharges,
        miscphonecharges,
        miscadmissionkit,
        miscorthopedic,
        dateused,
        provideraccess,
        retrievedforapproval,
        recreated,
        origloacode,
        benefitclass,
        contractno,
        plancode,
        finalstatus,
        roomamount,
        calleremail,
        streetaddress,
        province,
        municipality,
        barangay,
        last_update_date
    )
select
    a.loacode,
    a.loadate,
    a.loano,
    a.claimtype,
    a.subclaimtype,
    a.callername,
    a.callercontact,
    a.compcode,
    hmspioneer.dbo.decrypt (a.companyname) AS companyname,
    a.companystatus,
    a.membercode,
    a.memberno,
    hmspioneer.dbo.decrypt (a.membername) AS membername,
    a.membertype,
    a.membercategory,
    a.levelcode,
    a.memberstatus,
    a.principalcode,
    hmspioneer.dbo.decrypt (a.principalname) AS principalname,
    a.principalno,
    a.classorder,
    a.policydivision,
    a.providercode,
    a.dateavailed,
    a.datedischarged,
    a.loastatus,
    a.eligibilitystatus,
    a.loaamount,
    a.dateapproved,
    a.datedue,
    a.approvedby,
    a.oldplancode,
    a.planname,
    a.roomtype,
    a.coveredfrom,
    a.coveredto,
    a.birthdate,
    a.gender,
    a.vip,
    a.origeffectivity,
    a.intervininggroup,
    a.creditedamount,
    a.sharedplan,
    a.admittingtext,
    a.doctorcode,
    a.doctorname,
    a.otherexclusions,
    a.procedures,
    a.icdno,
    a.remarks,
    a.dateencoded,
    a.encodedend,
    a.encodedby,
    a.encodedduration,
    a.rowmarker,
    a.loaconcerndesc,
    a.loaconcernno,
    a.loarequestcode,
    a.withguaranteeletter,
    a.controlno,
    a.philhealth,
    a.miscrnb,
    a.miscrnbamount,
    a.miscancillary,
    a.miscancillaryamount,
    a.miscproffee,
    a.miscproffeeamount,
    a.miscmbl,
    a.miscmblamount,
    a.misctakehome,
    a.misctakehomeamount,
    a.miscothers,
    a.miscothersamount,
    a.misccharges,
    a.miscphonecharges,
    a.miscadmissionkit,
    a.miscorthopedic,
    a.dateused,
    a.provideraccess,
    a.retrievedforapproval,
    a.recreated,
    a.origloacode,
    a.benefitclass,
    a.contractno,
    a.plancode,
    a.finalstatus,
    a.roomamount,
    a.calleremail,
    a.streetaddress,
    a.province,
    a.municipality,
    a.barangay,
    ISNULL (
        (
            SELECT
                MAX(b.datecreated)
            FROM
                hmspioneer.dbo.tblloajournal b
            WHERE
                b.loacode = a.loacode
        ),
        a.dateencoded
    ) AS last_update_date
from
    hmspioneer.dbo.tblloas a
WHERE
    1 = 1
    AND CAST(a.dateencoded AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(b.datecreated) AS DATE)
        FROM
            hmspioneer.dbo.tblloajournal b
        WHERE
            b.loacode = a.loacode
    ) = CAST(GETDATE () - 1 AS DATE);

----------------------------------------------6------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tbldoctorspecialization
WHERE
    1 = 1
    AND CAST(last_update_date AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into dpt_tbldoctorspecialization
INSERT INTO
    stg_hmspioneer.dbo.dpt_tbldoctorspecialization (
        detno,
        doctorcode,
        specialization,
        superspecs,
        shortspecs,
        shortsuperspecs,
        society,
        importedcode,
        last_update_date
    )
select
    a.detno,
    a.doctorcode,
    a.specialization,
    a.superspecs,
    a.shortspecs,
    a.shortsuperspecs,
    a.society,
    a.importedcode,
    isnull (
        (
            select
                max(b.datecreated)
            from
                hmspioneer.dbo.tbldoctorsjournal b
            where
                b.doctorcode = a.doctorcode
        ),
        c.dateencoded
    ) as last_update_date
from
    hmspioneer.dbo.tbldoctorspecialization a
    left join hmspioneer.dbo.tbldoctors c on c.doctorcode = a.doctorcode
where
    1 = 1
    --AND a.doctorcode <> 0
    AND CAST(c.dateencoded AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(b.datecreated) as date)
        FROM
            hmspioneer.dbo.tbldoctorsjournal b
        WHERE
            b.doctorcode = a.doctorcode
    ) = CAST(GETDATE () - 1 AS DATE);

----------------------------------------------7------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblsoaaccounts
WHERE
    1 = 1
    AND CAST(last_update_date AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into dpt_tblsoaaccounts
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblsoaaccounts (
        soacode,
        soano,
        soadate,
        soadue,
        compcode,
        billingcompcode,
        soatype,
        statuscode,
        soaamount,
        paidamount,
        datepaid,
        vatpercent,
        commissionamount,
        grossamount,
        glamount,
        extrarate,
        coveredfrom,
        coveredto,
        discount,
        contractcode,
        generatedby,
        dategenerated,
        datereleased,
        releasedby,
        importedcode,
        referenceno,
        billingschedule,
        jvnoar,
        jvnoreversal,
        uploaded,
        billtype,
        rowmarker,
        adjamount,
        gpadminrate,
        gpadminfee,
        consolidatedcode,
        migrated,
        lifeamount,
        medicalamount,
        mastercode,
        agentno,
        remarks,
        replacement,
        replacesoacode,
        cancelconsolidatedcode,
        dateapproved,
        billingmodal,
        cancelmasterarcode,
        datecancelled,
        cdamount,
        otherdeductions,
        slagentno,
        soadueextension,
        currentaddressee,
        policydivision,
        collectionstatus,
        vattype,
        vatamount,
        companyfeedetno,
        grossamountriders,
        dstamount,
        premiumtax,
        localtax,
        netpremium,
        vatexempt,
        vatsales,
        vatoutput,
        billingagentno,
        groupno,
        additional,
        xlsmemberattachment,
        manualrenewal,
        withMAD,
        classorder,
        additionalamount,
        additionalpay,
        additionalsoacode,
        billngtype,
        cncimportedcode,
        dateencoded,
        encodedby,
        parentcompcode,
        last_update_date
    )
SELECT
    a.soacode,
    a.soano,
    a.soadate,
    a.soadue,
    a.compcode,
    a.billingcompcode,
    a.soatype,
    a.statuscode,
    a.soaamount,
    a.paidamount,
    a.datepaid,
    a.vatpercent,
    a.commissionamount,
    a.grossamount,
    a.glamount,
    a.extrarate,
    a.coveredfrom,
    a.coveredto,
    a.discount,
    a.contractcode,
    a.generatedby,
    a.dategenerated,
    a.datereleased,
    a.releasedby,
    a.importedcode,
    a.referenceno,
    a.billingschedule,
    a.jvnoar,
    a.jvnoreversal,
    a.uploaded,
    a.billtype,
    a.rowmarker,
    a.adjamount,
    a.gpadminrate,
    a.gpadminfee,
    a.consolidatedcode,
    a.migrated,
    a.lifeamount,
    a.medicalamount,
    a.mastercode,
    a.agentno,
    a.remarks,
    a.replacement,
    a.replacesoacode,
    a.cancelconsolidatedcode,
    a.dateapproved,
    a.billingmodal,
    a.cancelmasterarcode,
    a.datecancelled,
    a.cdamount,
    a.otherdeductions,
    a.slagentno,
    a.soadueextension,
    a.currentaddressee,
    a.policydivision,
    a.collectionstatus,
    a.vattype,
    a.vatamount,
    a.companyfeedetno,
    a.grossamountriders,
    a.dstamount,
    a.premiumtax,
    a.localtax,
    a.netpremium,
    a.vatexempt,
    a.vatsales,
    a.vatoutput,
    a.billingagentno,
    a.groupno,
    a.additional,
    a.xlsmemberattachment,
    a.manualrenewal,
    a.withMAD,
    a.classorder,
    a.additionalamount,
    a.additionalpay,
    a.additionalsoacode,
    a.billngtype,
    a.cncimportedcode,
    a.dateencoded,
    a.encodedby,
    a.parentcompcode,
    ISNULL (
        (
            select
                max(b.dateencoded)
            from
                hmspioneer.dbo.tblsoaaccountsjournal b
            where
                b.soacode = a.soacode
        ),
        a.dategenerated
    ) as last_update_date
FROM
    hmspioneer.dbo.TBLSOAACCOUNTS a
WHERE
    1 = 1
    AND CAST(a.soadate AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(b.dateencoded) AS DATE)
        FROM
            hmspioneer.dbo.tblsoaaccountsjournal b
        WHERE
            b.soacode = a.soacode
    ) = CAST(GETDATE () - 1 AS DATE);

;

----------------------------------------------8------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblusers
WHERE
    1 = 1
    AND CAST(last_update_date AS DATE) >= CAST(GETDATE () AS DATE);

;

-- Insert data into dpt_tblusers
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblusers (
        userno,
        usercode,
        username,
        userpass,
        useraccess,
        usertype,
        userpicture,
        nickname,
        activetask,
        activeuser,
        lastaccess,
        workstation,
        rememberpc,
        branchno,
        subbranchno,
        departmentno,
        emailadd,
        defaultdir,
        passwordlock,
        passwordexpiry,
        strongpassword,
        invalidtime,
        invalidattempt,
        accountindex,
        designation,
        cashier,
        employeeno,
        rowmarker,
        divisioncode,
        dashboard,
        datecreated,
        inactivedate,
        mobileno,
        tempno,
        tfa,
        lastcashierseries,
        passwordhash,
        passwordsalt,
        daterequestforgotpass,
        requestforgotpassguid,
        branchnos,
        digitalsignature,
        last_update_date
    )
SELECT
    a.userno,
    a.usercode,
    a.username,
    a.userpass,
    a.useraccess,
    a.usertype,
    a.userpicture,
    a.nickname,
    a.activetask,
    a.activeuser,
    a.lastaccess,
    a.workstation,
    a.rememberpc,
    a.branchno,
    a.subbranchno,
    a.departmentno,
    a.emailadd,
    a.defaultdir,
    a.passwordlock,
    a.passwordexpiry,
    a.strongpassword,
    a.invalidtime,
    a.invalidattempt,
    a.accountindex,
    a.designation,
    a.cashier,
    a.employeeno,
    a.rowmarker,
    a.divisioncode,
    a.dashboard,
    a.datecreated,
    a.inactivedate,
    a.mobileno,
    a.tempno,
    a.tfa,
    a.lastcashierseries,
    a.passwordhash,
    a.passwordsalt,
    a.daterequestforgotpass,
    a.requestforgotpassguid,
    a.branchnos,
    a.digitalsignature,
    ISNULL (
        (
            select
                max(b.datecreated)
            from
                hmspioneer.dbo.TBLUSERJOURNAL b
            where
                b.userno = a.userno
        ),
        a.datecreated
    ) as last_update_date
FROM
    hmspioneer.dbo.TBLUSERS a
WHERE
    1 = 1
    AND CAST(a.datecreated AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(b.datecreated) AS DATE)
        FROM
            hmspioneer.dbo.TBLUSERJOURNAL b
        WHERE
            b.userno = a.userno
    ) = CAST(GETDATE () - 1 AS DATE);

----------------------------------------------9------------------------------------------------------
-- Clear data from table
DELETE FROM stg_hmspioneer.dbo.dpt_tblcompanybenefitplan
WHERE
    1 = 1
    AND CAST(last_update_date AS DATE) >= CAST(GETDATE () AS DATE);

-- Insert data into dpt_tblusers
INSERT INTO
    stg_hmspioneer.dbo.dpt_tblcompanybenefitplan (
        plancode,
        planname,
        compcode,
        contractcode,
        membertype,
        membertypemajor,
        sobplancode,
        sobmajorcode,
        limitamount,
        limitamountac,
        limitamountmajor,
        limitamountspillover,
        classification,
        claimservices,
        claimserviceitems,
        provideraccess,
        philhealth,
        remarks,
        coinsurance,
        coinsurancemajor,
        coinsurancespillover,
        deductible,
        deductiblemajor,
        deductiblespillover,
        deductiblere,
        deductiblemajorre,
        deductiblespilloverre,
        interperiodprin,
        interperioddep,
        interperiodddprin,
        interperioddddep,
        billingschedule,
        applicablegender,
        preparedby,
        prepareddate,
        actuaryby,
        actuarydate,
        approvedby,
        approveddate,
        rowmarker,
        usemajormed,
        membertypespillover,
        limitamountmajorac,
        sharedmajorlimit,
        sharedspillover,
        effectivity,
        expiry,
        reimbursementrate,
        productcode,
        oldplancode,
        migrated,
        retail,
        retailplancode,
        vattype,
        groupcode,
        plandesc,
        coinsurancelimit,
        renewalplancode,
        programtype,
        pecwaived,
        selectiontype,
        validityperiod,
        registrationperiod,
        activationdays,
        registrationused,
        registrationunused,
        sumassured,
        agefrom,
        ageto,
        plantype,
        withsobimage,
        displaysalesportal,
        ilbundled,
        adminfee,
        amdtcode,
        archive,
        benefitclassdetno,
        brokerfee,
        callless,
        classcode,
        clbufferlimit,
        coininnerlimit,
        coinsurancemajorre,
        coinsurancere,
        coinsurancespilloverre,
        computeinner,
        customplancode,
        excessguarantee,
        hibamount,
        mobile,
        prorated,
        sharedlimit,
        privilegecare,
        benefittype,
        limitsetup,
        pedsetup,
        coveredafter,
        premiumfeeamount,
        last_update_date
    )
select
    a.plancode,
    a.planname,
    a.compcode,
    a.contractcode,
    a.membertype,
    a.membertypemajor,
    a.sobplancode,
    a.sobmajorcode,
    a.limitamount,
    a.limitamountac,
    a.limitamountmajor,
    a.limitamountspillover,
    a.classification,
    a.claimservices,
    a.claimserviceitems,
    a.provideraccess,
    a.philhealth,
    a.remarks,
    a.coinsurance,
    a.coinsurancemajor,
    a.coinsurancespillover,
    a.deductible,
    a.deductiblemajor,
    a.deductiblespillover,
    a.deductiblere,
    a.deductiblemajorre,
    a.deductiblespilloverre,
    a.interperiodprin,
    a.interperioddep,
    a.interperiodddprin,
    a.interperioddddep,
    a.billingschedule,
    a.applicablegender,
    a.preparedby,
    a.prepareddate,
    a.actuaryby,
    a.actuarydate,
    a.approvedby,
    a.approveddate,
    a.rowmarker,
    a.usemajormed,
    a.membertypespillover,
    a.limitamountmajorac,
    a.sharedmajorlimit,
    a.sharedspillover,
    a.effectivity,
    a.expiry,
    a.reimbursementrate,
    a.productcode,
    a.oldplancode,
    a.migrated,
    a.retail,
    a.retailplancode,
    a.vattype,
    a.groupcode,
    a.plandesc,
    a.coinsurancelimit,
    a.renewalplancode,
    a.programtype,
    a.pecwaived,
    a.selectiontype,
    a.validityperiod,
    a.registrationperiod,
    a.activationdays,
    a.registrationused,
    a.registrationunused,
    a.sumassured,
    a.agefrom,
    a.ageto,
    a.plantype,
    a.withsobimage,
    a.displaysalesportal,
    a.ilbundled,
    a.adminfee,
    a.amdtcode,
    a.archive,
    a.benefitclassdetno,
    a.brokerfee,
    a.callless,
    a.classcode,
    a.clbufferlimit,
    a.coininnerlimit,
    a.coinsurancemajorre,
    a.coinsurancere,
    a.coinsurancespilloverre,
    a.computeinner,
    a.customplancode,
    a.excessguarantee,
    a.hibamount,
    a.mobile,
    a.prorated,
    a.sharedlimit,
    a.privilegecare,
    a.benefittype,
    a.limitsetup,
    a.pedsetup,
    a.coveredafter,
    a.premiumfeeamount,
    ISNULL (
        (
            select
                max(b.datecreated)
            from
                hmspioneer.dbo.tblcompanybenefitjournal b
            where
                b.plancode = a.plancode
        ),
        a.prepareddate
    ) as last_update_date
from
    hmspioneer.dbo.tblcompanybenefitplan a
WHERE
    1 = 1
    AND CAST(a.prepareddate AS DATE) = CAST(GETDATE () - 1 AS DATE)
    OR (
        SELECT
            CAST(MAX(b.datecreated) AS DATE)
        FROM
            hmspioneer.dbo.tblcompanybenefitjournal b
        WHERE
            b.plancode = a.plancode
    ) = CAST(GETDATE () - 1 AS DATE);

;

-- Close the symmetric key
EXEC hmspioneer.dbo.sp_closesymmetric;

-- Commit the transaction
COMMIT TRANSACTION;

END TRY BEGIN CATCH
-- Rollback in case of error
ROLLBACK TRANSACTION;

-- Print error message
PRINT ERROR_MESSAGE ();

END CATCH END;